### PR TITLE
Fix disabled calibrate mag button

### LINKED ISSUE #245: Calibrate magnetometer button greyed out
I have the Omnibus F4 V3. Holybro Ublox NEO-M8N GPS Module with HMC5883L digital compass. the Holybro does turn green and start to flash the blue led(?) after start time on the unit. When i enable the Mag to this unit INAV causes the ready light on the Omnibus FC to flash rapidly. I assume this is because the compass has not been calibrated. IF i turn off the MAG the flashing stops. Anyway i do not  know if this is a Hardware problem or INAV. So, Can not fly. NO Calibrate Compass button.

Please advise

Thanks

### PR DESCRIPTION
**Pull request by digitalentity**
Looks like we have a possible race condition in Setup tab code between `periodicStatusUpdater` and `TABS.setup.initialize`. 

On connect `CONFIG.activeSensors` is zero. If `TABS.setup.initialize` calls `process_html` before `periodicStatusUpdater` polls for sensor status "Calibrate magnetometer" button will be disabled.

This PR queries for `MSP_STATUS_EX` message explicitly.

Should resolve #245, #162

### CODE REVIEW

**Comment by digitalentity** [comment]
@DzikuVx @fiam please review

File: js/msp/MSPHelper.js [hunk 1]
```diff
@@ -1957,6 +1957,10 @@ var mspHelper = (function (gui) {
         MSP.send_message(MSPCodes.MSP_BF_CONFIG, false, false, callback);
     };
 
+    self.quaryFcStatus = function (callback) {
```
Comment (DzikuVx) [inline js/msp/MSPHelper.js]: `queryFcStatus` not `quaryFcStatus`

Comment (digitalentity) [reply js/msp/MSPHelper.js]: Fixed!
